name: Commit Sync

on:
  push:
    branches:
     - master
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  sync-commits:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    - name: Run commit sync
      env:
        GL_USERNAME: ${{ secrets.GL_USERNAME }}
        GH_REPOSITORY: ${{ secrets.GH_REPOSITORY }}
        GH_USERNAME: ${{ secrets.GH_USERNAME }}
        GH_EMAIL: ${{ secrets.GH_EMAIL }}
      run: ./script.sh
